### PR TITLE
Support `unique_id:`

### PR DESCRIPTION
**Pull request by HarvsG**

### CODE REVIEW

**Comment by lolouk44** [comment]
Thanks a lot @HarvsG for your contribution.
I no longer use my CurrentCost so can't test it.
From a quick glance it looks ok.
I take it you've fully tested this?

**Comment by HarvsG** [comment]
Not tested yet. I'll let you know when I have

**Comment by HarvsG** [comment]
tested on 2021.9 for annoying reasons

before:
image


after:
image

**Comment by HarvsG** [comment]
Want me to put a version bump in the PR?

**Comment by lolouk44** [comment]
Thanks for this. You can bump the version indeed if you want to help a bit more. I can then create a new release so it's picked up by HACS

**Comment by HarvsG** [comment]
Done

**Comment by lolouk44** [comment]
Thanks. The [developer documentation page](https://developers.home-assistant.io/docs/entity_registry_index/) states that the unique_id really shouldn't be set up in the config,

> It is important that it is not possible for the user to change the unique ID, because the system would lose all its settings related to the unique ID.

I've not dealt with unique_ids in the past so don't have experience of setting them up, but could it not be set up in the sensor code? I'm not sure where you're located, I'm base in the UK (GMT+1 until end of month) and can be reached on discord under user lolouk44 #7180 if you want to discuss this?

**Comment by HarvsG** [comment]
I think that applies to integrations that are configured by config-flow:

PRs that add in configuration.yaml unique IDs are still being accepted
https://github.com/home-assistant/core/pull/77461/files

And it is listed as YAML keys in a number of native integrations:
https://www.home-assistant.io/integrations/template/#unique_id

**Pull request merged**
